snowflake-dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: hy48871.us-central1.gcp

      # User/password auth
      user: usuario
      password: senha

      role: role
      database: database
      warehouse: dw
      schema: schema
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt-q

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false